services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-gluetun_server_1
      APP_PORT: 8080
      # Use this if another app outside your umbrel device wants to connect via an API call
      PROXY_AUTH_WHITELIST: /api/*
      # Set false if another app from outside your umbrell wants to connect without login in!
      PROXY_AUTH_ADD: 'false'

  server:
    image: lscr.io/linuxserver/sabnzbd:latest
    network_mode: "container:martinmeel-gluetun_server_1"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads/complete:/downloads
      - ${UMBREL_ROOT}/home/Downloads/incomplete:/incomplete-downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    # Note: No ports section needed - using Gluetun's exposed port 8989
    restart: unless-stopped
    stop_grace_period: 1m