services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-gluetun_server_1
      APP_PORT: 8080

  server:
    image: lscr.io/linuxserver/sabnzbd:latest
    network_mode: "container:martinmeel-gluetun_server_1"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads/complete:/complete
      - ${UMBREL_ROOT}/home/Downloads/incomplete:/incomplete-downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    stop_grace_period: 1m