services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-profilarr_server_1
      APP_PORT: 6868

  server:
    image: santiagosayshey/profilarr:latest
    #network_mode: "container:martinmeel-gluetun_server_1"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    ports:
      - 6868:6868
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    stop_grace_period: 1m




    services:
    profilarr:
        image: santiagosayshey/profilarr:latest # Use :beta for early access to new features
        container_name: profilarr
        ports:
            - 6868:6868
        volumes:
            - /path/to/your/data:/config # Replace with your actual path
        environment:
            - TZ=UTC # Set your timezone
        restart: unless-stopped