services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-profilarr_server_1
      APP_PORT: 5858

  server:
    image: santiagosayshey/profilarr:latest
    #network_mode: "container:martinmeel-gluetun_server_1"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    ports:
      - 5858:6868
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam