services:
  #app_proxy:
  #  environment:
  #    APP_HOST: martinmeel-profilarr_server_1
  #    APP_PORT: 6868
  #    PROXY_AUTH_ADD: false
  server:
    image: santiagosayshey/profilarr:latest
    network_mode: "container:martinmeel-gluetun_server_1"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    ports:
      - 6868:6868
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    stop_grace_period: 1m