services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-gluetun_server_1
      APP_PORT: 9705
      #PROXY_AUTH_ADD: false
  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    network_mode: "container:martinmeel-gluetun_server_1"
    #ports:
    #  - "9705:9705"
    volumes:
    - ${APP_DATA_DIR}/data/config:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Amsterdam
    restart: unless-stopped