services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-sonarr_server_1
      APP_PORT: 2929
      #PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: lscr.io/linuxserver/sonarr:4.0.16
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads/TVSeries:/tv
      - ${UMBREL_ROOT}/home/Downloads/TVSeriesOLD:/tvold
      - ${UMBREL_ROOT}/home/Downloads/complete:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 2929:8989
    restart: unless-stopped
    stop_grace_period: 1m